
export function getEmailContent({ type, data }: { type: string; data?: any }) {
  let subject = '';
  let htmlContent = '';

  switch (type) {
    case 'welcome':
      subject = 'Bem-vindo à Homes Design';
      htmlContent = `
        <!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Bem-vindo à Homes Designs</title></head><body style="margin:0; padding:0; font-family: Arial, sans-serif; background-color:#f8f9fc;"><table align="center" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px; margin:20px auto; background:#ffffff; border-radius:8px; overflow:hidden; border:1px solid #e5e7eb;"><tr><td style="background:#111827; color:#ffffff; text-align:center; padding:20px;"><h1 style="margin:0; font-size:24px;">Homes Designs</h1><p style="margin:5px 0 0; font-size:14px; color:#d1d5db;">Transformando paredes em arte</p></td></tr><tr><td style="padding:30px; color:#111827;"><h2 style="margin-bottom:10px;">Seja muito bem-vindo(a)!</h2><p style="margin:0 0 15px; font-size:15px; line-height:22px;">Obrigado por se cadastrar em nosso site. Aqui na <strong>Homes Designs</strong>, somos apaixonados por dar vida aos ambientes através da arte.</p><p style="margin:0 0 15px; font-size:15px; line-height:22px;">Trabalhamos com quadros decorativos únicos e cuidadosamente selecionados, perfeitos para transformar qualquer espaço da sua casa ou escritório.</p><p style="margin:0 0 20px; font-size:15px; line-height:22px;">A partir de agora, você receberá novidades, ofertas exclusivas e inspirações incríveis diretamente no seu e-mail.</p><a href="https://homedecorinteriores.com" style="display:inline-block; background:#111827; color:#ffffff; text-decoration:none; padding:12px 20px; border-radius:6px; font-size:15px; font-weight:bold;">Visitar nossa loja</a></td></tr><tr><td style="background:#f3f4f6; text-align:center; padding:15px; font-size:12px; color:#6b7280;">© 2025 Homes Designs – Todos os direitos reservados<br><a href="https://homedecorinteriores.com" style="color:#3b82f6; text-decoration:none;">homedecorinteriores.com</a></td></tr></table></body></html>`;
      break;

    case 'orderPendingPayment':
        subject = `Seu pedido #${data.orderId.slice(0, 8)} está aguardando pagamento`;
        htmlContent = `
            <!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Aguardando Pagamento</title></head><body style="margin:0; padding:0; font-family: 'Segoe UI', sans-serif; background-color:#f7f7f7;"><table align="center" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px; margin:20px auto; background:#ffffff; border-radius:8px; overflow:hidden;"><tr><td style="background:#4a6cf7; color:#ffffff; text-align:center; padding:20px;"><h1 style="margin:0; font-size:24px;">Homes Designs</h1><p style="margin:5px 0 0; font-size:14px; color:#e0e0e0;">Pedido Recebido</p></td></tr><tr><td style="padding:30px; color:#3d3d3d;"><h2 style="margin-bottom:10px;">Olá, ${data.customerName}!</h2><p style="margin:0 0 15px; font-size:15px; line-height:22px;">Seu pedido foi registrado em nosso sistema e está <strong>aguardando confirmação de pagamento</strong>.</p><div style="background:#fff8e6; border-left:4px solid #ffc107; padding:15px; margin:20px 0; border-radius:0 4px 4px 0;"><p style="margin:0;">Seu pedido só será processado após a confirmação do pagamento.</p></div><div style="background:#f5f7fa; padding:12px; border-radius:4px; text-align:center; font-weight:600; margin:15px 0;">Pedido: <strong>#${data.orderId.slice(0, 8)}</strong> • Total: <strong>R$ ${data.total.toFixed(2).replace('.', ',')}</strong></div><p>Caso já tenha efetuado o pagamento, por favor desconsidere este e-mail. O status será atualizado em breve.</p><a href="https://homedecorinteriores.com/checkout" style="display:block; background:#4CAF50; color:white; text-align:center; padding:14px 20px; border-radius:4px; text-decoration:none; font-weight:600; margin:20px 0;">FINALIZAR PAGAMENTO</a><p>Agradecemos pela sua compra!<br><strong>Equipe Homes Designs</strong></p></td></tr><tr><td style="background:#f3f4f6; text-align:center; padding:15px; font-size:12px; color:#6b7280;">© 2025 Homes Designs – Todos os direitos reservados<br><a href="https://homedecorinteriores.com" style="color:#3b82f6; text-decoration:none;">homedecorinteriores.com</a></td></tr></table></body></html>`;
        break;

    case 'newSaleAdmin':
        subject = `🎉 Nova Venda Realizada! Pedido #${data.orderId.slice(0, 8)}`;
        htmlContent = `
            <!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Nova Venda</title></head><body style="font-family:'Segoe UI',sans-serif; background-color:#f4f4f4; margin:0; padding:0;"><table align="center" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px; margin:20px auto; background:#ffffff; border-radius:8px; overflow:hidden;"><tr style="background-color:#2c3e50; color:white; text-align:center;"><td style="padding:20px;"><h1 style="margin:0; font-size:24px;">Nova Venda!</h1></td></tr><tr><td style="padding:30px;"><p style="font-size:18px;">Parabéns! Uma nova venda foi realizada:</p><div style="background-color:#f9f9f9; border-left:4px solid #3498db; padding:15px; margin:20px 0; border-radius:0 4px 4px 0;"><p><strong>Pedido:</strong> #${data.orderId.slice(0, 8)}</p><p><strong>Cliente:</strong> ${data.customerName}</p><p><strong>Valor:</strong> R$ ${data.total.toFixed(2).replace('.', ',')}</p><p><strong>Itens:</strong></p><ul>${data.items.map((item: any) => `<li>${item.quantity}x ${item.name}</li>`).join('')}</ul></div><div style="text-align:center;"><a href="https://homedecorinteriores.com/dashboard/orders" style="display:inline-block; background:#3498db; color:#ffffff; padding:12px 25px; text-decoration:none; border-radius:5px; margin-top:20px;">Ver Pedido no Painel</a></div></td></tr><tr style="background-color:#f3f4f6; text-align:center; font-size:12px; color:#6b7280;"><td style="padding:15px;"><p>© 2025 Homes Designs</p></td></tr></table></body></html>`;
        break;
        
    case 'orderApproved':
      subject = `✅ Compra Aprovada - Pedido #${data.orderId.slice(0, 8)}`;
      htmlContent = `
        <!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Compra Aprovada</title></head><body style="margin:0; padding:0; font-family: Arial, sans-serif; background-color:#f8f9fc;"><table align="center" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px; margin:20px auto; background:#ffffff; border-radius:8px; overflow:hidden; border:1px solid #e5e7eb;"><tr><td style="background:#16a34a; color:#ffffff; text-align:center; padding:20px;"><h1 style="margin:0; font-size:24px;">Compra Aprovada</h1><p style="margin:5px 0 0; font-size:14px; color:#d1fae5;">Obrigado por comprar na Homes Designs</p></td></tr><tr><td style="padding:30px; color:#111827;"><h2 style="margin-bottom:10px;">Olá, ${data.customerName}! Seu pedido foi confirmado!</h2><p style="margin:0 0 15px; font-size:15px; line-height:22px;">Sua compra <strong>#${data.orderId.slice(0, 8)}</strong> foi aprovada e já estamos preparando tudo para o envio.</p><p style="margin:0 0 20px; font-size:15px; line-height:22px;">Você receberá um novo e-mail com o código de rastreio assim que o pedido for despachado.</p><a href="https://homedecorinteriores.com/dashboard/my-orders/${data.orderId}" style="display:inline-block; background:#16a34a; color:#ffffff; text-decoration:none; padding:12px 20px; border-radius:6px; font-size:15px; font-weight:bold;">Acompanhar pedido</a></td></tr><tr><td style="background:#f3f4f6; text-align:center; padding:15px; font-size:12px; color:#6b7280;">© 2025 Homes Designs – Todos os direitos reservados<br><a href="https://homedecorinteriores.com" style="color:#3b82f6; text-decoration:none;">homedecorinteriores.com</a></td></tr></table></body></html>`;
      break;

    case 'orderShipped':
      subject = `🚚 Seu pedido #${data.orderId.slice(0, 8)} está a caminho!`;
      htmlContent = `
        <!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Seu pedido está a caminho</title></head><body style="margin:0; padding:0; font-family: Arial, sans-serif; background-color:#f8f9fc;"><table align="center" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px; margin:20px auto; background:#ffffff; border-radius:8px; overflow:hidden; border:1px solid #e5e7eb;"><tr><td style="background:#2563eb; color:#ffffff; text-align:center; padding:20px;"><h1 style="margin:0; font-size:24px;">Seu pedido está a caminho</h1><p style="margin:5px 0 0; font-size:14px; color:#dbeafe;">Homes Designs</p></td></tr><tr><td style="padding:30px; color:#111827;"><h2 style="margin-bottom:10px;">Boa notícia, ${data.customerName}!</h2><p style="margin:0 0 15px; font-size:15px; line-height:22px;">Seu pedido <strong>#${data.orderId.slice(0, 8)}</strong> já foi enviado e está a caminho do seu endereço.</p><p style="margin:0 0 20px; font-size:15px; line-height:22px;">Para mais detalhes e acompanhar a entrega em tempo real, clique no botão abaixo.</p><a href="https://homedecorinteriores.com/dashboard/my-orders/${data.orderId}" style="display:inline-block; background:#2563eb; color:#ffffff; text-decoration:none; padding:12px 20px; border-radius:6px; font-size:15px; font-weight:bold;">Acompanhar Entrega</a></td></tr><tr><td style="background:#f3f4f6; text-align:center; padding:15px; font-size:12px; color:#6b7280;">© 2025 Homes Designs – Todos os direitos reservados<br><a href="https://homedecorinteriores.com" style="color:#3b82f6; text-decoration:none;">homedecorinteriores.com</a></td></tr></table></body></html>`;
      break;

    case 'orderDelivered':
      subject = `✨ Seu pedido #${data.orderId.slice(0, 8)} foi entregue!`;
      htmlContent = `
        <!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Seu pedido foi entregue</title></head><body style="margin:0; padding:0; font-family: Arial, sans-serif; background-color:#f8f9fc;"><table align="center" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px; margin:20px auto; background:#ffffff; border-radius:8px; overflow:hidden; border:1px solid #e5e7eb;"><tr><td style="background:#16a34a; color:#ffffff; text-align:center; padding:20px;"><h1 style="margin:0; font-size:24px;">Pedido Entregue!</h1><p style="margin:5px 0 0; font-size:14px; color:#d1fae5;">Aproveite sua nova arte!</p></td></tr><tr><td style="padding:30px; color:#111827;"><h2 style="margin-bottom:10px;">Sua arte chegou, ${data.customerName}!</h2><p style="margin:0 0 15px; font-size:15px; line-height:22px;">Ótima notícia! Nosso sistema indica que seu pedido <strong>#${data.orderId.slice(0, 8)}</strong> foi entregue com sucesso.</p><p style="margin:0 0 20px; font-size:15px; line-height:22px;">Esperamos que você ame seus novos quadros tanto quanto nós amamos criá-los. Adoraríamos ver como ficou! Compartilhe uma foto nas redes sociais e marque a gente.</p><a href="https://homedecorinteriores.com" style="display:inline-block; background:#16a34a; color:#ffffff; text-decoration:none; padding:12px 20px; border-radius:6px; font-size:15px; font-weight:bold;">Visitar Loja</a></td></tr><tr><td style="background:#f3f4f6; text-align:center; padding:15px; font-size:12px; color:#6b7280;">© 2025 Homes Designs – Todos os direitos reservados<br><a href="https://homedecorinteriores.com" style="color:#3b82f6; text-decoration:none;">homedecorinteriores.com</a></td></tr></table></body></html>`;
      break;

    case 'orderCancelled':
      subject = `Pedido #${data.orderId.slice(0, 8)} Cancelado`;
      htmlContent = `
        <!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><title>Seu pedido foi cancelado</title></head><body style="margin:0; padding:0; font-family: Arial, sans-serif; background-color:#f8f9fc;"><table align="center" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px; margin:20px auto; background:#ffffff; border-radius:8px; overflow:hidden; border:1px solid #e5e7eb;"><tr><td style="background:#dc2626; color:#ffffff; text-align:center; padding:20px;"><h1 style="margin:0; font-size:24px;">Pedido Cancelado</h1><p style="margin:5px 0 0; font-size:14px; color:#fee2e2;">Homes Designs</p></td></tr><tr><td style="padding:30px; color:#111827;"><h2 style="margin-bottom:10px;">Aviso sobre o seu pedido</h2><p style="margin:0 0 15px; font-size:15px; line-height:22px;">Olá ${data.customerName}, informamos que o seu pedido <strong>#${data.orderId.slice(0, 8)}</strong> na Homes Designs foi cancelado.</p><p style="margin:0 0 20px; font-size:15px; line-height:22px;">Se você não solicitou o cancelamento ou tiver alguma dúvida, por favor, entre em contato com nosso suporte ao cliente.</p><a href="https://homedecorinteriores.com" style="display:inline-block; background:#dc2626; color:#ffffff; text-decoration:none; padding:12px 20px; border-radius:6px; font-size:15px; font-weight:bold;">Entrar em Contato</a></td></tr><tr><td style="background:#f3f4f6; text-align:center; padding:15px; font-size:12px; color:#6b7280;">© 2025 Homes Designs – Todos os direitos reservados<br><a href="https://homedecorinteriores.com" style="color:#3b82f6; text-decoration:none;">homedecorinteriores.com</a></td></tr></table></body></html>`;
      break;

    case 'refundRequestAdmin':
      subject = `Nova Solicitação de Devolução - Pedido #${data.orderId.slice(0, 8)}`;
      const photoLinks = data.photoUrls.map((url: string, index: number) => `<a href="${url}" style="margin-right:10px; text-decoration:none; display:inline-block; border:1px solid #ccc; padding:5px; border-radius:4px;">Ver Foto ${index + 1}</a>`).join('');
      htmlContent = `
            <!DOCTYPE html><html lang="pt-BR"><body style="margin:0; padding:0; font-family: Arial, sans-serif;"><table align="center" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px; background:#ffffff;"><tr><td style="background:#ffc107; color:#000000; text-align:center; padding:20px;"><h1 style="margin:0;">Nova Solicitação de Devolução</h1></td></tr><tr><td style="padding:30px;"><h2 style="margin-bottom:10px;">Detalhes da Solicitação</h2><p><strong>Pedido ID:</strong> #${data.orderId.slice(0, 8)}</p><p><strong>Cliente:</strong> ${data.customerEmail}</p><p><strong>Motivo:</strong></p><p style="padding:10px; background-color:#f8f9fa; border:1px solid #dee2e6; border-radius:4px;">${data.reason}</p>${data.photoUrls.length > 0 ? `<p><strong>Fotos Anexadas:</strong></p><div>${photoLinks}</div>` : ''}<a href="https://homedecorinteriores.com/dashboard/orders" style="display:inline-block; background:#007bff; color:#ffffff; text-decoration:none; padding:12px 20px; border-radius:6px; margin-top:20px;">Gerenciar Pedido</a></td></tr></table></body></html>`;
      break;

    case 'refundRequestCustomer':
      subject = `Sua Solicitação de Devolução Foi Recebida (Pedido #${data.orderId.slice(0, 8)})`;
      htmlContent = `
            <!DOCTYPE html><html lang="pt-BR"><body style="margin:0; padding:0; font-family: Arial, sans-serif;"><table align="center" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px; background:#ffffff;"><tr><td style="background:#17a2b8; color:#ffffff; text-align:center; padding:20px;"><h1 style="margin:0;">Solicitação Recebida</h1></td></tr><tr><td style="padding:30px;"><h2 style="margin-bottom:10px;">Olá, ${data.customerName}</h2><p>Recebemos sua solicitação de devolução para o pedido <strong>#${data.orderId.slice(0, 8)}</strong>.</p><p>Nossa equipe irá analisar o seu pedido e entrará em contato em breve com os próximos passos.</p><p>Obrigado pela sua paciência.</p><a href="https://homedecorinteriores.com/dashboard/my-orders" style="display:inline-block; background:#17a2b8; color:#ffffff; text-decoration:none; padding:12px 20px; border-radius:6px; margin-top:20px;">Ver Meus Pedidos</a></td></tr></table></body></html>`;
      break;
    
    default:
        return { subject: '', htmlContent: '' };
  }

  return { subject, htmlContent };
}
