
export const products = [
  {
    id: '1',
    name: 'Explosão Cromática',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'abstract painting',
    hint_alt: 'living room',
    category: 'Abstrato',
    arrangement: 'Solo',
  },
  {
    id: '2',
    name: 'Selva Esmeralda',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'botanical print',
    hint_alt: 'bedroom wall',
    category: 'Botânico',
    arrangement: 'Solo',
  },
  {
    id: '3',
    name: 'Coração de Pixel',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'pixel art',
    hint_alt: 'office decor',
    category: 'Geek',
    arrangement: 'Solo',
  },
  {
    id: '4',
    name: 'Linhas Serenas',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'minimalist art',
    hint_alt: 'hallway art',
    category: 'Minimalista',
    arrangement: 'Solo',
  },
  {
    id: '5',
    name: 'Rei Leão Geométrico',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://i0.wp.com/www.papeldeparede.etc.br/wp-content/uploads/2022/07/imagem-de-uma-sala-com-o-quadro-de-leao-geometrico_Easy-Resize.com_.jpg?resize=1000%2C1000&ssl=1',
    hint: 'geometric lion',
    hint_alt: 'modern office',
    category: 'Animais',
    arrangement: 'Dupla',
  },
  {
    id: '6',
    name: 'Fé Iluminada',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://i0.wp.com/www.papeldeparede.etc.br/wp-content/uploads/2022/07/imagem-de-uma-sala-com-o-quadro-de-leao-geometrico_Easy-Resize.com_.jpg?resize=1000%2C1000&ssl=1',
    hint: 'faith quote',
    hint_alt: 'cozy living room',
    category: 'Religião',
    arrangement: 'Dupla',
  },
  {
    id: '7',
    name: 'Quadro Cavalo Branco',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'white horse',
    hint_alt: 'living room',
    category: 'Animais',
    arrangement: 'Solo',
  },
  {
    id: '8',
    name: 'Pássaros Tropicais',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'tropical birds',
    hint_alt: 'balcony decor',
    category: 'Animais',
    arrangement: 'Dupla',
  },
  {
    id: '9',
    name: 'Borboletas Coloridas',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'butterflies',
    hint_alt: 'study room',
    category: 'Animais',
    arrangement: 'Trio',
  },
  {
    id: '10',
    name: 'Patas Amigas',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'animal paws',
    hint_alt: 'kids room',
    category: 'Animais',
    arrangement: 'Dupla',
  },
  {
    id: '11',
    name: 'Lobo da Meia-Noite',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'wolf',
    hint_alt: 'modern living room',
    category: 'Animais',
    arrangement: 'Solo',
  },
  {
    id: '12',
    name: 'Rosa Solitária',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'single rose',
    hint_alt: 'bedroom',
    category: 'Floral',
    arrangement: 'Solo',
  },
  {
    id: '13',
    name: 'Dupla de Lírios',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'lily flowers',
    hint_alt: 'dining room',
    category: 'Floral',
    arrangement: 'Dupla',
  },
  {
    id: '14',
    name: 'Girassóis Vibrantes',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'sunflowers',
    hint_alt: 'kitchen',
    category: 'Floral',
    arrangement: 'Trio',
  },
  {
    id: '15',
    name: 'Salmo 23',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'psalm 23',
    hint_alt: 'prayer corner',
    category: 'Religião',
    arrangement: 'Solo',
  },
  {
    id: '16',
    name: 'A Criação',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'creation',
    hint_alt: 'church hall',
    category: 'Religião',
    arrangement: 'Dupla',
  },
  {
    id: '17',
    name: 'Versículos em Dupla',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'bible verses',
    hint_alt: 'office',
    category: 'Religião',
    arrangement: 'Trio',
  },
  {
    id: '18',
    name: 'Onda Abstrata',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'abstract wave',
    hint_alt: 'bathroom',
    category: 'Abstrato',
    arrangement: 'Solo',
  },
  {
    id: '19',
    name: 'Formas Geométricas',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'geometric shapes',
    hint_alt: 'modern office',
    category: 'Abstrato',
    arrangement: 'Dupla',
  },
  {
    id: '20',
    name: 'Névoa Minimalista',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'minimalist fog',
    hint_alt: 'zen room',
    category: 'Minimalista',
    arrangement: 'Solo',
  },
  {
    id: '21',
    name: 'Ponto e Linha',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'minimalist art',
    hint_alt: 'corridor',
    category: 'Minimalista',
    arrangement: 'Dupla',
  },
  {
    id: '22',
    name: 'Controlador Clássico',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'classic controller',
    hint_alt: 'game room',
    category: 'Geek',
    arrangement: 'Solo',
  },
  {
    id: '23',
    name: 'Naves Espaciais',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'space ship',
    hint_alt: 'game room',
    category: 'Geek',
    arrangement: 'Dupla',
  },
  {
    id: '24',
    name: 'Panda Fofo',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'cute panda',
    hint_alt: 'nursery room',
    category: 'Infantil',
    arrangement: 'Solo',
  },
  {
    id: '25',
    name: 'Dupla de Gatos Pretos',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'black cats',
    hint_alt: 'living room',
    category: 'Animais',
    arrangement: 'Dupla',
  },
   {
    id: 'A1',
    name: 'Sussurro da Savana',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'animal',
    hint_alt: 'room decor',
    category: 'Animais',
    arrangement: 'Solo',
  },
  {
    id: 'A2',
    name: 'Mergulho Ártico',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'animal',
    hint_alt: 'room decor',
    category: 'Animais',
    arrangement: 'Dupla',
  },
  {
    id: 'A3',
    name: 'Voo da Liberdade',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'animal',
    hint_alt: 'room decor',
    category: 'Animais',
    arrangement: 'Solo',
  },
  {
    id: 'A4',
    name: 'Abraço do Panda',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'animal',
    hint_alt: 'room decor',
    category: 'Animais',
    arrangement: 'Dupla',
  },
  {
    id: 'A5',
    name: 'Canto da Baleia',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'animal',
    hint_alt: 'room decor',
    category: 'Animais',
    arrangement: 'Solo',
  },
  {
    id: 'B1',
    name: 'Costela de Adão',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'botanical',
    hint_alt: 'room decor',
    category: 'Botânico',
    arrangement: 'Solo',
  },
  {
    id: 'B2',
    name: 'Folha de Bananeira',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'botanical',
    hint_alt: 'room decor',
    category: 'Botânico',
    arrangement: 'Dupla',
  },
  {
    id: 'B3',
    name: 'Jardim Suspenso',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'botanical',
    hint_alt: 'room decor',
    category: 'Botânico',
    arrangement: 'Solo',
  },
  {
    id: 'B4',
    name: 'Paraíso Tropical',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'botanical',
    hint_alt: 'room decor',
    category: 'Botânico',
    arrangement: 'Dupla',
  },
  {
    id: 'B5',
    name: 'Cacto do Deserto',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'botanical',
    hint_alt: 'room decor',
    category: 'Botânico',
    arrangement: 'Solo',
  },
  {
    id: 'C1',
    name: 'Buquê de Peônias',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'flower',
    hint_alt: 'room decor',
    category: 'Floral',
    arrangement: 'Solo',
  },
  {
    id: 'C2',
    name: 'Orquídea Delicada',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'flower',
    hint_alt: 'room decor',
    category: 'Floral',
    arrangement: 'Dupla',
  },
  {
    id: 'C3',
    name: 'Campo de Lavanda',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'flower',
    hint_alt: 'room decor',
    category: 'Floral',
    arrangement: 'Solo',
  },
  {
    id: 'C4',
    name: 'Tulipas ao Vento',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'flower',
    hint_alt: 'room decor',
    category: 'Floral',
    arrangement: 'Dupla',
  },
  {
    id: 'C5',
    name: 'Dália Vermelha',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'flower',
    hint_alt: 'room decor',
    category: 'Floral',
    arrangement: 'Solo',
  },
  {
    id: 'D1',
    name: 'Mãos em Oração',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'religion',
    hint_alt: 'room decor',
    category: 'Religião',
    arrangement: 'Solo',
  },
  {
    id: 'D2',
    name: 'Cruz da Esperança',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'religion',
    hint_alt: 'room decor',
    category: 'Religião',
    arrangement: 'Dupla',
  },
  {
    id: 'D3',
    name: 'Espírito Santo em Dourado',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'religion',
    hint_alt: 'room decor',
    category: 'Religião',
    arrangement: 'Solo',
  },
  {
    id: 'D4',
    name: 'O Bom Pastor',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'religion',
    hint_alt: 'room decor',
    category: 'Religião',
    arrangement: 'Dupla',
  },
  {
    id: 'D5',
    name: 'Santa Ceia Minimalista',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'religion',
    hint_alt: 'room decor',
    category: 'Religião',
    arrangement: 'Solo',
  },
  {
    id: 'E1',
    name: 'Conexões Neurais',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'abstract',
    hint_alt: 'room decor',
    category: 'Abstrato',
    arrangement: 'Solo',
  },
  {
    id: 'E2',
    name: 'Sonata em Azul',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'abstract',
    hint_alt: 'room decor',
    category: 'Abstrato',
    arrangement: 'Dupla',
  },
  {
    id: 'E3',
    name: 'Tempestade de Areia',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'abstract',
    hint_alt: 'room decor',
    category: 'Abstrato',
    arrangement: 'Solo',
  },
  {
    id: 'E4',
    name: 'Aurora Boreal',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'abstract',
    hint_alt: 'room decor',
    category: 'Abstrato',
    arrangement: 'Dupla',
  },
  {
    id: 'E5',
    name: 'Caos Organizado',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'abstract',
    hint_alt: 'room decor',
    category: 'Abstrato',
    arrangement: 'Solo',
  },
  {
    id: 'F1',
    name: 'Traço Único',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'minimalist',
    hint_alt: 'room decor',
    category: 'Minimalista',
    arrangement: 'Solo',
  },
  {
    id: 'F2',
    name: 'Círculo Perfeito',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'minimalist',
    hint_alt: 'room decor',
    category: 'Minimalista',
    arrangement: 'Dupla',
  },
  {
    id: 'F3',
    name: 'Equilíbrio Zen',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'minimalist',
    hint_alt: 'room decor',
    category: 'Minimalista',
    arrangement: 'Solo',
  },
  {
    id: 'F4',
    name: 'Sussurro do Vento',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'minimalist',
    hint_alt: 'room decor',
    category: 'Minimalista',
    arrangement: 'Dupla',
  },
  {
    id: 'F5',
    name: 'Ponto de Fuga',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'minimalist',
    hint_alt: 'room decor',
    category: 'Minimalista',
    arrangement: 'Solo',
  },
  {
    id: 'G1',
    name: 'Aventura na Selva',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'kids',
    hint_alt: 'room decor',
    category: 'Infantil',
    arrangement: 'Solo',
  },
  {
    id: 'G2',
    name: 'Monstrinhos Amigáveis',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'kids',
    hint_alt: 'room decor',
    category: 'Infantil',
    arrangement: 'Dupla',
  },
  {
    id: 'G3',
    name: 'Viagem Espacial',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'kids',
    hint_alt: 'room decor',
    category: 'Infantil',
    arrangement: 'Solo',
  },
  {
    id: 'G4',
    name: 'Reino dos Dinossauros',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'kids',
    hint_alt: 'room decor',
    category: 'Infantil',
    arrangement: 'Dupla',
  },
  {
    id: 'G5',
    name: 'Festa do Pijama',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'kids',
    hint_alt: 'room decor',
    category: 'Infantil',
    arrangement: 'Solo',
  },
  {
    id: 'H1',
    name: 'Carpe Diem',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'quotes',
    hint_alt: 'room decor',
    category: 'Frases/Tipografia',
    arrangement: 'Solo',
  },
  {
    id: 'H2',
    name: 'Sonhe Alto',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'quotes',
    hint_alt: 'room decor',
    category: 'Frases/Tipografia',
    arrangement: 'Dupla',
  },
  {
    id: 'H3',
    name: 'Apenas Respire',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'quotes',
    hint_alt: 'room decor',
    category: 'Frases/Tipografia',
    arrangement: 'Solo',
  },
  {
    id: 'H4',
    name: 'Lar Doce Lar',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'quotes',
    hint_alt: 'room decor',
    category: 'Frases/Tipografia',
    arrangement: 'Dupla',
  },
  {
    id: 'H5',
    name: 'Faça Acontecer',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'quotes',
    hint_alt: 'room decor',
    category: 'Frases/Tipografia',
    arrangement: 'Solo',
  },
  {
    id: 'I1',
    name: 'Cidade sob a Chuva',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'photography',
    hint_alt: 'room decor',
    category: 'Fotografia',
    arrangement: 'Solo',
  },
  {
    id: 'I2',
    name: 'Pôr do Sol na Praia',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'photography',
    hint_alt: 'room decor',
    category: 'Fotografia',
    arrangement: 'Dupla',
  },
  {
    id: 'I3',
    name: 'Escadaria em Espiral',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'photography',
    hint_alt: 'room decor',
    category: 'Fotografia',
    arrangement: 'Solo',
  },
  {
    id: 'I4',
    name: 'Retrato Anônimo',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'photography',
    hint_alt: 'room decor',
    category: 'Fotografia',
    arrangement: 'Dupla',
  },
  {
    id: 'I5',
    name: 'Luzes de Neon',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'photography',
    hint_alt: 'room decor',
    category: 'Fotografia',
    arrangement: 'Solo',
  },
  {
    id: 'J1',
    name: 'Croqui de Moda',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'fashion',
    hint_alt: 'room decor',
    category: 'Fashion',
    arrangement: 'Solo',
  },
  {
    id: 'J2',
    name: 'Salto Alto',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'fashion',
    hint_alt: 'room decor',
    category: 'Fashion',
    arrangement: 'Dupla',
  },
  {
    id: 'J3',
    name: 'Olhar da Passarela',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'fashion',
    hint_alt: 'room decor',
    category: 'Fashion',
    arrangement: 'Solo',
  },
  {
    id: 'J4',
    name: 'Costura Fina',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'fashion',
    hint_alt: 'room decor',
    category: 'Fashion',
    arrangement: 'Dupla',
  },
  {
    id: 'J5',
    name: 'Elegância em Preto e Branco',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'fashion',
    hint_alt: 'room decor',
    category: 'Fashion',
    arrangement: 'Solo',
  },
  {
    id: 'K1',
    name: 'Silhueta Feminina',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'femme',
    hint_alt: 'room decor',
    category: 'Femme',
    arrangement: 'Solo',
  },
  {
    id: 'K2',
    name: 'Força da Mulher',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'femme',
    hint_alt: 'room decor',
    category: 'Femme',
    arrangement: 'Dupla',
  },
  {
    id: 'K3',
    name: 'Olhar de Confiança',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'femme',
    hint_alt: 'room decor',
    category: 'Femme',
    arrangement: 'Solo',
  },
  {
    id: 'K4',
    name: 'Florescer Interior',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'femme',
    hint_alt: 'room decor',
    category: 'Femme',
    arrangement: 'Dupla',
  },
  {
    id: 'K5',
    name: 'Curvas em Linhas',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://www.papeleparede.com.br/4402-large_default/papel-de-parede-com-fundo-palha-e-detalhes-em-bege.jpg',
    hint: 'femme',
    hint_alt: 'room decor',
    category: 'Femme',
    arrangement: 'Solo',
  },
  {
    id: 'L1',
    name: 'Dragão Místico',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'mystical dragon',
    hint_alt: 'fantasy room',
    category: 'Geek',
    arrangement: 'Solo'
  },
  {
    id: 'L2',
    name: 'Guerreiros Espaciais',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'space warriors',
    hint_alt: 'sci-fi room',
    category: 'Geek',
    arrangement: 'Dupla'
  },
  {
    id: 'L3',
    name: 'Portal Dimensional',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'dimensional portal',
    hint_alt: 'modern office geek',
    category: 'Geek',
    arrangement: 'Trio'
  },
  {
    id: 'L4',
    name: 'Unicórnio Programador',
    price: 0,
    image: 'https://placehold.co/800x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'unicorn programmer',
    hint_alt: 'developer office',
    category: 'Geek',
    arrangement: 'Dupla'
  },
  {
    id: 'L5',
    name: 'Fantasma Divertido',
    price: 0,
    image: 'https://placehold.co/400x500.png',
    image_alt: 'https://placehold.co/800x600.png',
    hint: 'funny ghost',
    hint_alt: 'kids game room',
    category: 'Geek',
    arrangement: 'Solo'
  }
];

export const compositions = [
    { id: 'c1', name: 'Galeria Monocromática', image: 'https://placehold.co/600x400.png', hint: 'gallery wall' },
    { id: 'c2', name: 'Splash Pop Art', image: 'https://placehold.co/600x400.png', hint: 'colorful living room' },
    { id: 'c3', name: 'Sonho Boêmio', image: 'https://placehold.co/600x400.png', hint: 'boho bedroom' },
    { id: 'c4', name: 'Calma Nórdica', image: 'https://placehold.co/600x400.png', hint: 'scandinavian interior' },
];

export const testimonials = [
    {
        name: "Jéssica P.",
        avatar: "https://placehold.co/100x100.png",
        hint: "woman portrait",
        rating: 5,
        quote: "A qualidade é incrível e ficou deslumbrante na minha sala. As sugestões de composição da IA foram perfeitas!"
    },
    {
        name: "Miguel R.",
        avatar: "https://placehold.co/100x100.png",
        hint: "man smiling",
        rating: 5,
        quote: "Envio rápido e a impressão era ainda mais vibrante pessoalmente. Usei o chatbot para uma pergunta e obtive uma resposta instantânea e útil."
    },
    {
        name: "Chloe T.",
        avatar: "https://placehold.co/100x100.png",
        hint: "person selfie",
        rating: 4,
        quote: "Adoro os designs exclusivos. Meu único desejo é por mais opções de tamanho, mas no geral foi uma ótima experiência."
    }
];

export const collections = [
  { slug: 'animais', name: 'Animais', image: 'https://cdn6.campograndenews.com.br/uploads/noticias/2023/01/20/691c73dd24a60411b5bc65d4329035a56bba629e.jpeg', hint: 'elephant' },
  { slug: 'floral', name: 'Floral', image: 'https://img.freepik.com/vetores-gratis/padrao-floral-abstrato-plano-organico_23-2148923571.jpg?semt=ais_hybrid&w=740', hint: 'flower' },
  { slug: 'abstrato', name: 'Abstrato', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS667S4SsyCpYH6HuZ_ysVwnzFHV4_nHbdkcA&s', hint: 'abstract' },
  { slug: 'frases-tipografia', name: 'Frases/Tipografia', image: 'https://i.pinimg.com/736x/56/de/96/56de96ac38decccabbbf516fb85b025a.jpg', hint: 'typography' },
  { slug: 'botanico', name: 'Botânico', image: 'https://i.pinimg.com/236x/93/30/12/933012248c7da55d48e93e14ee8134f9.jpg', hint: 'botanical' },
  { slug: 'geek', name: 'Geek', image: 'https://img.elo7.com.br/product/zoom/32B191E/quadro-decorativo-desenho-capitao-america-geek-comico-quadro-filmes.jpg', hint: 'game controller' },
  { slug: 'fotografia', name: 'Fotografia', image: 'https://a-static.mlcdn.com.br/800x560/quadro-arte-abstrata-cidade-europeia-ki-art-quadros-decorativos/oliststore/mgl8fkfftqb5zmnn/55c04a7ccb3cede0d14df1da0a3f991e.jpeg', hint: 'camera' },
  { slug: 'infantil', name: 'Infantil', image: 'https://blog-leiturinha-novo.s3.us-east-1.amazonaws.com/production/uploads/2023/05/babyshark.jpg', hint: 'hedgehog' },
  { slug: 'fashion', name: 'Fashion', image: 'https://cdn.11.vuzi.com.br/goquadros/product/404401.webp', hint: 'fashion' },
  { slug: 'minimalista', name: 'Minimalista', image: 'https://st2.depositphotos.com/8815532/44724/v/450/depositphotos_447247498-stock-illustration-one-line-drawing-face-abstract.jpg', hint: 'line art face' },
  { slug: 'femme', name: 'Femme', image: 'https://medias.artmajeur.com/home/14141927_17c76aac-e019-48f9-af9d-a05a7a6aa5c1.jpg?v=1739181916', hint: 'woman face' },
  { slug: 'religiao', name: 'Religião', image: 'https://carolinarochas.com.br/wp-content/uploads/2025/03/Pintura-sacra-de-Jesus-Cristo-pintado-a-mao.jpg', hint: 'jesus christ painting' },
];
