

export const products = [
  // --- Produto de Teste ---
  { id: 'TEST-01', name: 'Produto de Teste', price: 0.50, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'test product', hint_alt: 'living room', category: 'Minimalista', arrangement: 'Teste', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },

  // --- Coleção Animais ---
  { id: 'AN-S1', name: 'Leão Majestoso', price: 75.00, image: 'https://iili.io/F4dSPrF.jpg', image_alt: 'https://iili.io/F4dS4qP.jpg', artwork_image: 'https://i.ibb.co/s91GxBq8/download-1.jpg', hint: 'lion', hint_alt: 'living room', category: 'Animais', arrangement: 'Solo', imagesByColor: { black: 'https://iili.io/F4dSPrF.jpg', white: 'https://iili.io/F4dSUXV.jpg', hazel_oak: 'https://iili.io/F4dS611.png', ebony_oak: 'https://iili.io/F4dSgLB.jpg' } },
  { id: 'AN-S2', name: 'Águia Soberana', price: 75.00, image: 'https://iili.io/F42eBbp.png', image_alt: 'https://iili.io/F42eKdJ.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'eagle', hint_alt: 'living room', category: 'Animais', arrangement: 'Solo', imagesByColor: { black: 'https://iili.io/F42eBbp.png', white: 'https://iili.io/F42eHs1.jpg', hazel_oak: 'https://iili.io/F42e3ga.jpg', ebony_oak: 'https://iili.io/F42edqF.jpg' } },
  { id: 'AN-D1', name: 'Dança dos Golfinhos', price: 175.00, image: 'https://iili.io/F4KI2kv.png', image_alt: 'https://iili.io/F4KIdYJ.jpg', artwork_image: 'https://placehold.co/800x500.png', hint: 'dolphins', hint_alt: 'bathroom decor', category: 'Animais', arrangement: 'Dupla', imagesByColor: { black: 'https://iili.io/F4KI2kv.png', white: 'https://iili.io/F4KIJ2a.jpg', hazel_oak: 'https://iili.io/F4KI9rg.jpg', ebony_oak: 'https://iili.io/F4KzyEF.jpg' } },
  { id: 'AN-D2', name: 'Cavalos Selvagens', price: 175.00, image: 'https://iili.io/F4KKyZu.png', image_alt: 'https://iili.io/F4KKtvS.jpg', artwork_image: 'https://placehold.co/800x500.png', hint: 'horses', hint_alt: 'rustic house', category: 'Animais', arrangement: 'Dupla', imagesByColor: { black: 'https://iili.io/F4KKyZu.png', white: 'https://iili.io/F4KKDy7.jpg', hazel_oak: 'https://iili.io/F4KKmu9.jpg', ebony_oak: 'https://iili.io/F4KKpje.jpg' } },
  { id: 'AN-T1', name: 'Camaleão, Esquilo e Coelho', price: 260.00, image: 'https://iili.io/F4gHPDv.png', image_alt: 'https://iili.io/F4gHUUF.jpg', artwork_image: 'https://placehold.co/1200x500.png', hint: 'chameleon squirrel rabbit', hint_alt: 'playroom', category: 'Animais', arrangement: 'Trio', imagesByColor: { black: 'https://iili.io/F4gHPDv.png', white: 'https://iili.io/F4gH4Ra.png', hazel_oak: 'https://iili.io/F4gH6OJ.png', ebony_oak: 'https://iili.io/F4gHrHg.png' } },
  { id: 'AN-T2', name: 'Família Urso', price: 260.00, image: 'https://iili.io/F4U6wJI.png', image_alt: 'https://iili.io/F4U6GWJ.jpg', artwork_image: 'https://placehold.co/1200x500.png', hint: 'bears', hint_alt: 'cabin decor', category: 'Animais', arrangement: 'Trio', imagesByColor: { black: 'https://iili.io/F4U6wJI.png', white: 'https://iili.io/F4U6Miv.png', hazel_oak: 'https://iili.io/F4U6Xlp.png', ebony_oak: 'https://iili.io/F4U6WfR.png' } },
  
  // --- Coleção Floral (2 Solo, 2 Dupla, 2 Trio) ---
  { id: 'FL-S1', name: 'Rosa Solitária', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'rose', hint_alt: 'living room', category: 'Floral', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'FL-S2', name: 'Girassol Radiante', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'sunflower', hint_alt: 'living room', category: 'Floral', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'FL-D1', name: 'Par de Lírios', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'lilies', hint_alt: 'living room', category: 'Floral', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'FL-D2', name: 'Buquê Duplo', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'bouquets', hint_alt: 'hallway', category: 'Floral', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'FL-T1', name: 'Jardim Secreto', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'secret garden', hint_alt: 'vintage room', category: 'Floral', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },
  { id: 'FL-T2', name: 'Primavera Eterna', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'spring flowers', hint_alt: 'bright room', category: 'Floral', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },

  // --- Coleção Abstrato ---
  { id: 'AB-S1', name: 'Caos Controlado', price: 75.00, image: 'https://iili.io/F6gObtt.png', image_alt: 'https://iili.io/F6gOZ9p.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'abstract art', hint_alt: 'living room', category: 'Abstrato', arrangement: 'Solo', imagesByColor: { black: 'https://iili.io/F6gObtt.png', white: 'https://iili.io/F6gOLSR.jpg', hazel_oak: 'https://iili.io/F6gOiKJ.jpg', ebony_oak: 'https://iili.io/F6gObtt.png' } },
  { id: 'AB-S2', name: 'Pincelada Única', price: 75.00, image: 'https://iili.io/F6gvcFa.png', image_alt: 'https://iili.io/F6gvY6g.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'brush stroke', hint_alt: 'living room', category: 'Abstrato', arrangement: 'Solo', imagesByColor: { black: 'https://iili.io/F6gvcFa.png', white: 'https://iili.io/F6gvuwB.jpg', hazel_oak: 'https://iili.io/F6gv7MF.jpg', ebony_oak: 'https://iili.io/F6gvAZP.jpg' } },
  { id: 'AB-D1', name: 'Geometria Líquida', price: 175.00, image: 'https://iili.io/F6rxZMJ.png', image_alt: 'https://iili.io/F6rxiwF.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'liquid geometry', hint_alt: 'modern bedroom', category: 'Abstrato', arrangement: 'Dupla', imagesByColor: { black: 'https://iili.io/F6rxZMJ.png', white: 'https://iili.io/F6rxsZg.png', hazel_oak: 'https://iili.io/F6rxQna.png', ebony_oak: 'https://iili.io/F6rxPu1.jpg' } },
  { id: 'AB-D2', name: 'Nuvem de Tinta', price: 175.00, image: 'https://iili.io/F6rlst4.png', image_alt: 'https://iili.io/F6rl8PI.jpg', artwork_image: 'https://placehold.co/800x500.png', hint: 'ink cloud', hint_alt: 'balanced interior', category: 'Abstrato', arrangement: 'Dupla', imagesByColor: { black: 'https://iili.io/F6rlst4.png', white: 'https://iili.io/F6rlgcX.png', hazel_oak: 'https://iili.io/F6rlPAG.png', ebony_oak: 'https://iili.io/F6rlrSn.png' } },
  { id: 'AB-T1', name: 'Evolução da Forma', price: 260.00, image: 'https://iili.io/F6r1E21.png', image_alt: 'https://iili.io/F6r17hx.jpg', artwork_image: 'https://placehold.co/1200x500.png', hint: 'shape evolution', hint_alt: 'gallery wall', category: 'Abstrato', arrangement: 'Trio', imagesByColor: { black: 'https://iili.io/F6r1E21.png', white: 'https://iili.io/F6r1YLQ.png', hazel_oak: 'https://iili.io/F6r1lEB.png', ebony_oak: 'https://iili.io/F6r1cBV.png' } },
  { id: 'AB-T2', name: 'Ciclos da Vida', price: 260.00, image: 'https://iili.io/F6rVOts.png', image_alt: 'https://iili.io/F6rVWcN.jpg', artwork_image: 'https://placehold.co/1200x500.png', hint: 'life cycles', hint_alt: 'holistic center', category: 'Abstrato', arrangement: 'Trio', imagesByColor: { black: 'https://iili.io/F6rVOts.png', white: 'https://iili.io/F6rVXSI.png', hazel_oak: 'https://iili.io/F6rVj9t.png', ebony_oak: 'https://iili.io/F6rVwAX.png' } },

  // --- Coleção Frases/Tipografia (2 Solo, 2 Dupla, 2 Trio) ---
  { id: 'TP-S1', name: 'Inspire', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'inspire quote', hint_alt: 'living room', category: 'Frases/Tipografia', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'TP-S2', name: 'Sonhe', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'dream quote', hint_alt: 'living room', category: 'Frases/Tipografia', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'TP-D1', name: 'Lar Doce Lar', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'home sweet home', hint_alt: 'house entrance', category: 'Frases/Tipografia', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'TP-D2', name: 'Café & Coragem', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'coffee courage', hint_alt: 'coffee shop', category: 'Frases/Tipografia', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'TP-T1', name: 'Viva, Ria, Ame', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'live laugh love', hint_alt: 'family room', category: 'Frases/Tipografia', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },
  { id: 'TP-T2', name: 'Mente, Corpo, Alma', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'mind body soul', hint_alt: 'wellness center', category: 'Frases/Tipografia', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },

  // --- Coleção Botânico (2 Solo, 2 Dupla, 2 Trio) ---
  { id: 'BT-S1', name: 'Folha de Monstera', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'monstera leaf', hint_alt: 'living room', category: 'Botânico', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'BT-S2', name: 'Cacto Solitário', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'cactus', hint_alt: 'living room', category: 'Botânico', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'BT-D1', name: 'Folhas de Palmeira', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'palm leaves', hint_alt: 'resort vibe', category: 'Botânico', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'BT-D2', name: 'Jardim Vertical', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'vertical garden', hint_alt: 'balcony', category: 'Botânico', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'BT-T1', name: 'Floresta Encantada', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'enchanted forest', hint_alt: 'fantasy bedroom', category: 'Botânico', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },
  { id: 'BT-T2', name: 'Coleção de Suculentas', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'succulents collection', hint_alt: 'bright office', category: 'Botânico', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },

  // --- Coleção Geek (2 Solo, 2 Dupla, 2 Trio) ---
  { id: 'GK-S1', name: 'Pixel Art', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'pixel art', hint_alt: 'living room', category: 'Geek', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'GK-S2', name: 'Controle Clássico', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'classic controller', hint_alt: 'living room', category: 'Geek', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'GK-D1', name: 'Player 1 & Player 2', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'player one two', hint_alt: 'couple gamer', category: 'Geek', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'GK-D2', name: 'O Bem contra o Mal', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'good vs evil', hint_alt: 'themed room', category: 'Geek', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'GK-T1', name: 'A Jornada do Herói', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'hero journey', hint_alt: 'story wall', category: 'Geek', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },
  { id: 'GK-T2', name: 'Evolução do Videogame', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'game evolution', hint_alt: 'entertainment room', category: 'Geek', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },

  // --- Coleção Fotografia (2 Solo, 2 Dupla, 2 Trio) ---
  { id: 'PH-S1', name: 'Horizonte de NY', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'new york skyline', hint_alt: 'living room', category: 'Fotografia', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'PH-S2', name: 'Praia Deserta', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'deserted beach', hint_alt: 'living room', category: 'Fotografia', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'PH-D1', name: 'Preto e Branco Urbano', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'urban black white', hint_alt: 'industrial loft', category: 'Fotografia', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'PH-D2', name: 'Arquitetura Moderna', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'modern architecture', hint_alt: 'clean design', category: 'Fotografia', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'PH-T1', name: 'Fases da Lua', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'moon phases', hint_alt: 'astronomy lover', category: 'Fotografia', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },
  { id: 'PH-T2', name: 'Trilogia Parisiense', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'paris trilogy', hint_alt: 'romantic decor', category: 'Fotografia', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },

  // --- Coleção Infantil (2 Solo, 2 Dupla, 2 Trio) ---
  { id: 'IN-S1', name: 'Meu Amigo Robô', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'robot friend', hint_alt: 'living room', category: 'Infantil', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'IN-S2', name: 'Unicórnio Mágico', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'magic unicorn', hint_alt: 'living room', category: 'Infantil', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'IN-D1', name: 'Sol e Lua Amigos', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'sun moon friends', hint_alt: 'shared bedroom', category: 'Infantil', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'IN-D2', name: 'Animais da Fazenda', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'farm animals', hint_alt: 'playful room', category: 'Infantil', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'IN-T1', name: 'Alfabeto Animal', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'animal alphabet', hint_alt: 'learning space', category: 'Infantil', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },
  { id: 'IN-T2', name: 'Aventura na Selva', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'jungle adventure', hint_alt: 'themed nursery', category: 'Infantil', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },

  // --- Coleção Fashion (2 Solo, 2 Dupla, 2 Trio) ---
  { id: 'FA-S1', name: 'Croqui Elegante', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'elegant sketch', hint_alt: 'living room', category: 'Fashion', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'FA-S2', name: 'Salto Agulha', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'stiletto heel', hint_alt: 'living room', category: 'Fashion', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'FA-D1', name: 'Passarela de Paris', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'paris runway', hint_alt: 'chic apartment', category: 'Fashion', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'FA-D2', name: 'Sapatos & Bolsas', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'shoes bags', hint_alt: 'fashion corner', category: 'Fashion', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'FA-T1', name: 'Ícones da Moda', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'fashion icons', hint_alt: 'style gallery', category: 'Fashion', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },
  { id: 'FA-T2', name: 'As Capitais da Moda', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'fashion capitals', hint_alt: 'world traveler', category: 'Fashion', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },

  // --- Coleção Minimalista (2 Solo, 2 Dupla, 2 Trio) ---
  { id: 'MI-S1', name: 'Linha Contínua', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'continuous line', hint_alt: 'living room', category: 'Minimalista', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'MI-S2', name: 'Ponto de Fuga', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'vanishing point', hint_alt: 'living room', category: 'Minimalista', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'MI-D1', name: 'Equilíbrio e Harmonia', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'balance harmony', hint_alt: 'feng shui', category: 'Minimalista', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'MI-D2', name: 'Composições Simétricas', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'symmetrical composition', hint_alt: 'organized space', category: 'Minimalista', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'MI-T1', name: 'Trilogia da Simplicidade', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'simplicity trilogy', hint_alt: 'clear space', category: 'Minimalista', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },
  { id: 'MI-T2', name: 'Sequência Lógica', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'logical sequence', hint_alt: 'rational design', category: 'Minimalista', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },
  
  // --- Coleção Femme (2 Solo, 2 Dupla, 2 Trio) ---
  { id: 'FE-S1', name: 'Olhar Penetrante', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'female gaze', hint_alt: 'living room', category: 'Femme', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'FE-S2', name: 'Silhueta em Curvas', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'curvy silhouette', hint_alt: 'living room', category: 'Femme', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'FE-D1', name: 'Sororidade', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'sorority sisterhood', hint_alt: 'female friendship', category: 'Femme', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'FE-D2', name: 'Mãe e Filha', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'mother daughter', hint_alt: 'family love', category: 'Femme', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'FE-T1', name: 'As Três Graças', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'three graces', hint_alt: 'classic art modern', category: 'Femme', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },
  { id: 'FE-T2', name: 'Ciclo Feminino', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'female cycle', hint_alt: 'natural rhythm', category: 'Femme', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },
  
  // --- Coleção Religião (2 Solo, 2 Dupla, 2 Trio) ---
  { id: 'RE-S1', name: 'Oração Silenciosa', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'silent prayer', hint_alt: 'living room', category: 'Religião', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'RE-S2', name: 'Cruz Minimalista', price: 75.00, image: 'https://placehold.co/400x500.png', image_alt: 'https://images.tcdn.com.br/img/img_prod/703418/papel_de_parede_adesivo_ariana_clean_756_1_20200217074948.jpg', artwork_image: 'https://placehold.co/400x500.png', hint: 'minimalist cross', hint_alt: 'living room', category: 'Religião', arrangement: 'Solo', imagesByColor: { black: 'https://placehold.co/600x800.png', white: 'https://placehold.co/600x800.png', hazel_oak: 'https://placehold.co/600x800.png', ebony_oak: 'https://placehold.co/600x800.png' } },
  { id: 'RE-D1', name: 'Fé e Esperança', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'faith hope', hint_alt: 'inspirational wall', category: 'Religião', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'RE-D2', name: 'Alfa e Ômega', price: 175.00, image: 'https://placehold.co/800x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/800x500.png', hint: 'alpha omega', hint_alt: 'symbolic decor', category: 'Religião', arrangement: 'Dupla', imagesByColor: { black: 'https://placehold.co/800x500.png', white: 'https://placehold.co/800x500.png', hazel_oak: 'https://placehold.co/800x500.png', ebony_oak: 'https://placehold.co/800x500.png' } },
  { id: 'RE-T1', name: 'Fé, Esperança, Amor', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'faith hope love', hint_alt: 'christian triptych', category: 'Religião', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },
  { id: 'RE-T2', name: 'Santíssima Trindade', price: 260.00, image: 'https://placehold.co/1200x500.png', image_alt: 'https://placehold.co/800x600.png', artwork_image: 'https://placehold.co/1200x500.png', hint: 'holy trinity', hint_alt: 'religious decor', category: 'Religião', arrangement: 'Trio', imagesByColor: { black: 'https://placehold.co/1200x500.png', white: 'https://placehold.co/1200x500.png', hazel_oak: 'https://placehold.co/1200x500.png', ebony_oak: 'https://placehold.co/1200x500.png' } },
];

export const compositions = [
    { id: 'c1', name: 'Galeria Monocromática', image: 'https://placehold.co/600x400.png', hint: 'gallery wall' },
    { id: 'c2', name: 'Splash Pop Art', image: 'https://placehold.co/600x400.png', hint: 'colorful living room' },
    { id: 'c3', name: 'Sonho Boêmio', image: 'https://placehold.co/600x400.png', hint: 'boho bedroom' },
    { id: 'c4', name: 'Calma Nórdica', image: 'https://placehold.co/600x400.png', hint: 'scandinavian interior' },
];

export const testimonials = [
    {
        name: "Jéssica P.",
        avatar: "https://placehold.co/100x100.png",
        hint: "woman portrait",
        rating: 5,
        quote: "A qualidade é incrível e ficou deslumbrante na minha sala. As sugestões de composição da IA foram perfeitas!"
    },
    {
        name: "Miguel R.",
        avatar: "https://placehold.co/100x100.png",
        hint: "man smiling",
        rating: 5,
        quote: "Envio rápido e a impressão era ainda mais vibrante pessoalmente. Usei o chatbot para uma pergunta e obtive uma resposta instantânea e útil."
    },
    {
        name: "Chloe T.",
        avatar: "https://placehold.co/100x100.png",
        hint: "person selfie",
        rating: 4,
        quote: "Adoro os designs exclusivos. Meu único desejo é por mais opções de tamanho, mas no geral foi uma ótima experiência."
    }
];

export const collections = [
  { slug: 'animais', name: 'Animais', image: 'https://cdn6.campograndenews.com.br/uploads/noticias/2023/01/20/691c73dd24a60411b5bc65d4329035a56bba629e.jpeg', hint: 'elephant' },
  { slug: 'floral', name: 'Floral', image: 'https://img.freepik.com/vetores-gratis/padrao-floral-abstrato-plano-organico_23-2148923571.jpg?semt=ais_hybrid&w=740', hint: 'flower' },
  { slug: 'abstrato', name: 'Abstrato', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS667S4SsyCpYH6HuZ_ysVwnzFHV4_nHbdkcA&s', hint: 'abstract' },
  { slug: 'frases-tipografia', name: 'Frases/Tipografia', image: 'https://i.pinimg.com/736x/56/de/96/56de96ac38decccabbbf516fb85b025a.jpg', hint: 'typography' },
  { slug: 'botanico', name: 'Botânico', image: 'https://i.pinimg.com/236x/93/30/12/933012248c7da55d48e93e14ee8134f9.jpg', hint: 'botanical' },
  { slug: 'geek', name: 'Geek', image: 'https://i.ibb.co/21gyDj9v/imagem-2025-08-03-192551359.png', hint: 'game controller' },
  { slug: 'fotografia', name: 'Fotografia', image: 'https://a-static.mlcdn.com.br/800x560/quadro-arte-abstrata-cidade-europeia-ki-art-quadros-decorativos/oliststore/mgl8fkfftqb5zmnn/55c04a7ccb3cede0d14df1da0a3f991e.jpeg', hint: 'camera' },
  { slug: 'infantil', name: 'Infantil', image: 'https://blog-leiturinha-novo.s3.us-east-1.amazonaws.com/production/uploads/2023/05/babyshark.jpg', hint: 'hedgehog' },
  { slug: 'fashion', name: 'Fashion', image: 'https://cdn.11.vuzi.com.br/goquadros/product/404401.webp', hint: 'fashion' },
  { slug: 'minimalista', name: 'Minimalista', image: 'https://st2.depositphotos.com/8815532/44724/v/450/depositphotos_447247498-stock-illustration-one-line-drawing-face-abstract.jpg', hint: 'line art face' },
  { slug: 'femme', name: 'Femme', image: 'https://medias.artmajeur.com/home/14141927_17c76aac-e019-48f9-af9d-a05a7a6aa5c1.jpg?v=1739181916', hint: 'woman face' },
  { slug: 'religiao', name: 'Religião', image: 'https://carolinarochas.com.br/wp-content/uploads/2025/03/Pintura-sacra-de-Jesus-Cristo-pintado-a-mao.jpg', hint: 'jesus christ painting' },
];

    

    




    

    




